import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState} from '../data/defaults.js';
import {migrate} from '../js/migrate.js';
import {validateState,splitTransaction} from '../js/models.js';
import {monthBudget} from '../js/budget.js';
import {mergeStates} from '../js/sync-merge.js';
import {cashNow,validCashTime,ensureCash,cashLedger,cashSummary,cashFingerprint,cashConnection,saveCashAccount,saveCashLink,saveCashCheck} from '../js/cash.js';
import {cashHome,cashView} from '../js/cash-ui.js';
const now='2026-10-08T20:00:00';
function state(){const s=emptyState();s.configured=true;ensureCash(s);return s;}
function account(s,id='a',amount=100000,owner='p1'){const a={id,name:id,owner,paymentMethod:'',openingBalance:amount,openingAt:'2026-09-30T23:59:59',reserved:0,autoMatch:false,archived:false};saveCashAccount(s,a,null,now);return a;}
function tx(s,id,amount=1000,direction='expense',extras={}){const t={id,sourceId:id,date:'2026-10-05',datetime:'2026-10-05T10:23:00',amount,direction,paymentMethod:'은행 계좌',merchantRaw:id,merchantNormalized:id,owner:'p1',scope:direction==='transfer'?'excluded':'shared',category:'other',excluded:direction==='transfer',deletedAt:null,...extras};s.transactions.push(t);return t;}
function link(s,t,a,direction='out',to){saveCashLink(s,t.id,[{accountId:a,direction,at:t.datetime},...(to?[{accountId:to,direction:'in',at:t.datetime}]:[])],false,cashFingerprint(t),now);}
function check(s,id='a',actual=100000,at='2026-10-08T18:00:00'){return saveCashCheck(s,{id:'check-'+id,accountId:id,at,actual,note:''},now);}
test('work category is additive and legacy classifications and budgets stay intact',()=>{const s=state();s.categories=s.categories.filter(c=>c.id!=='work');tx(s,'x',100,'expense',{category:'housing'});const before=JSON.stringify(s.transactions);migrate(s);migrate(s);assert.equal(s.categories.filter(c=>c.id==='work').length,1);assert.equal(s.categories.find(c=>c.id==='work').name,'업무경비');assert.equal(JSON.stringify(s.transactions),before);});
test('first current balance is only a baseline, not historical verification or new income',()=>{const s=state();account(s);const c=cashSummary(s,now);assert.equal(c.accounts[0].difference,null);assert.equal(c.baselineCount,1);assert.equal(s.transactions.length,0);assert.equal(c.actual,100000);});
test('incoming minus outgoing is reconciled against an unchanged starting balance',()=>{const s=state(),a=account(s);link(s,tx(s,'salary',50000,'income'),'a','in');link(s,tx(s,'food',12000),'a');check(s,'a',135000);const c=cashSummary(s,now).accounts[0];assert.equal(c.checked.incoming,50000);assert.equal(c.checked.outgoing,12000);assert.equal(c.checked.expected,138000);assert.equal(c.difference,-3000);assert.equal(s.transactions.length,2);assert.equal(a.openingBalance,100000);});
test('opposite discrepancies never cancel at household level',()=>{const s=state();account(s,'a');account(s,'b');check(s,'a',90000);check(s,'b',110000);const c=cashSummary(s,now);assert.equal(c.mismatchCount,2);assert.equal(c.absoluteDifference,20000);});
test('cash ledger uses actual timestamps, not 10-to-9 budget attribution',()=>{const s=state();const a=account(s);const t=tx(s,'x',3000,'expense',{operatingMonth:'2026-08'});link(s,t,'a');assert.equal(cashLedger(s,a,now).expected,97000);assert.equal(monthBudget(s,'2026-09','2026-10-08').spent,0);});
test('boundary timestamps are opening-exclusive and check-inclusive',()=>{const s=state(),a=account(s);for(const [id,time]of [['start',a.openingAt],['end','2026-10-08T18:00:00'],['after','2026-10-08T18:00:01']])link(s,tx(s,id,1000,'expense',{datetime:time,date:time.slice(0,10)}),'a');assert.equal(cashLedger(s,a,'2026-10-08T18:00:00').expected,99000);});
test('credit purchases are not cash while actual card bill withdrawals are included once',()=>{const s=state(),a=account(s);tx(s,'purchase',40000,'expense',{paymentMethod:'우리카드',sourceType:'card-woori-pdf'});const bill=tx(s,'card bill',40000,'transfer');link(s,bill,'a');assert.equal(cashLedger(s,a,now).expected,60000);assert.equal(monthBudget(s,'2026-09','2026-10-08').spent,40000);});
test('internal account transfer moves each balance but preserves total cash and spending',()=>{const s=state(),a=account(s,'a'),b=account(s,'b');const t=tx(s,'transfer',20000,'transfer');link(s,t,'a','out','b');assert.equal(cashLedger(s,a,now).expected,80000);assert.equal(cashLedger(s,b,now).expected,120000);assert.equal(cashSummary(s,now).expected,200000);assert.equal(monthBudget(s,'2026-09','2026-10-08').spent,0);});
test('nonoperating income and household-excluded cash expenses still change bank balances',()=>{const s=state(),a=account(s);link(s,tx(s,'insurance',7000,'income',{incomeKind:'nonoperating'}),'a','in');link(s,tx(s,'other',3000,'expense',{scope:'excluded',excluded:true}),'a');assert.equal(cashLedger(s,a,now).expected,104000);assert.equal(monthBudget(s,'2026-09','2026-10-08').actualIncome,0);});
test('scheduled recurring expenses are never fabricated bank withdrawals',()=>{const s=state(),a=account(s);s.recurring=[{id:'r',name:'insurance',amount:30000,day:5,category:'finance',owner:'joint',scope:'fixed',start:'2026-01-01',changes:[]}];assert.equal(cashLedger(s,a,now).expected,100000);assert.equal(s.transactions.length,0);});
test('reserves affect displayed usable cash only, not reconciliation or consumption',()=>{const s=state(),a=account(s);saveCashAccount(s,{...a,reserved:30000},a,now);check(s);const c=cashSummary(s,now);assert.equal(c.usable,70000);assert.equal(c.cash,undefined);assert.equal(c.accounts[0].difference,0);assert.equal(c.expected,100000);});
test('raw transaction edits invalidate explicit links until reconfirmed',()=>{const s=state(),a=account(s),t=tx(s,'x',5000);link(s,t,'a');check(s,'a',95000);t.amount=6000;let c=cashSummary(s,now).accounts[0];assert.equal(c.status,'review');assert.equal(c.checked.pending.length,1);assert.equal(c.recalculated,true);link(s,t,'a');c=cashSummary(s,now).accounts[0];assert.equal(c.checked.expected,94000);assert.equal(c.difference,1000);});
test('splitting one expense never doubles cash flow',()=>{const s=state(),a=account(s),t=tx(s,'x',10000);link(s,t,'a');s.transactions=splitTransaction(t,[{amount:4000,category:'work',scope:'shared'},{amount:6000,category:'other',scope:'shared'}]);assert.equal(cashLedger(s,a,now).outgoing,10000);assert.equal(cashLedger(s,a,now).entries.length,1);});
test('voiding only a balance observation keeps all transactions and the anchor',()=>{const s=state();account(s);check(s);const before=JSON.stringify(s.transactions);s.cashChecks[0].voidedAt='2026-10-08T18:01:00Z';assert.equal(cashSummary(s,now).accounts[0].difference,null);assert.equal(JSON.stringify(s.transactions),before);});
test('exact account binding requires user confirmation and does not guess transfer direction',()=>{const s=state(),a=account(s),t=tx(s,'x',1000);assert.equal(cashConnection(t,s).status,'unlinked');saveCashAccount(s,{...a,autoMatch:true,paymentMethod:'은행 계좌'},a,now);assert.equal(cashConnection(t,s).status,'auto');t.direction='transfer';assert.equal(cashConnection(t,s).status,'review');});
test('cash account binding never matches a card or default/unknown timestamp',()=>{const s=state(),a=account(s);assert.throws(()=>saveCashAccount(s,{...a,autoMatch:true,paymentMethod:'우리카드'},a,now));saveCashAccount(s,{...a,autoMatch:true,paymentMethod:'은행 계좌'},a,now);const t=tx(s,'x',1000,'expense',{datetime:'2026-10-05T12:00:00'});assert.equal(cashConnection(t,s).status,'review');});
test('cash links can ignore a duplicate bank representation without changing expenses',()=>{const s=state(),a=account(s),t=tx(s,'x',5000);const before=JSON.stringify(t);saveCashLink(s,t.id,[],true,'',now);assert.equal(cashLedger(s,a,now).expected,100000);assert.equal(JSON.stringify(t),before);assert.equal(monthBudget(s,'2026-09','2026-10-08').spent,5000);});
test('missing, duplicate, future, invalid and conflicting account values are rejected',()=>{const s=state(),a=account(s);assert.throws(()=>saveCashAccount(s,{...a,openingBalance:1},a,now));assert.throws(()=>saveCashCheck(s,{id:'x',accountId:'a',at:a.openingAt,actual:1},now));assert.throws(()=>saveCashCheck(s,{id:'x',accountId:'a',at:'2026-10-09T00:00:00',actual:1},now));check(s);assert.throws(()=>check(s));const b=structuredClone(s);b.cashAccounts[0].openingBalance=NaN;assert.throws(()=>validateState(b));assert.equal(validCashTime('2026-02-30T12:00:00'),false);assert.equal(validCashTime(cashNow()),true);});
test('one transfer cannot target the same account twice or two incoming legs',()=>{const s=state();account(s);account(s,'b');const t=tx(s,'x');assert.throws(()=>link(s,t,'a','out','a'));assert.throws(()=>saveCashLink(s,t.id,[{accountId:'a',direction:'in',at:t.datetime},{accountId:'b',direction:'in',at:t.datetime}],false,'',now));});
test('cash markup and search preserve personal merchant privacy and escape labels',()=>{const s=state();account(s);s.cashAccounts[0].name='<img src=x onerror=x>';tx(s,'private',1000,'expense',{merchantRaw:'SECRET MERCHANT',note:'SECRET NOTE',scope:'p1'});for(const html of[cashHome(s),cashView(s,{status:'all'})]){assert.ok(!html.includes('<img src=x'));assert.ok(!html.includes('SECRET MERCHANT'));assert.ok(!html.includes('SECRET NOTE'));}assert.ok(!cashView(s,{status:'all',query:'SECRET MERCHANT'}).includes('data-id="private"'));});
test('cash links and account edits are atomic conflicts, separate accounts can merge',()=>{const base=state();account(base);const local=structuredClone(base),remote=structuredClone(base);local.cashAccounts[0].reserved=1;remote.cashAccounts[0].name='other';assert.equal(mergeStates(base,local,remote).conflicts.length,1);const l=structuredClone(base),r=structuredClone(base);account(l,'b');account(r,'c');assert.equal(mergeStates(base,l,r).conflicts.length,0);assert.equal(mergeStates(base,l,r).state.cashAccounts.length,3);});
test('repeated read-only cash calculations leave all stored state unchanged',()=>{const s=state();const a=account(s);link(s,tx(s,'x'),'a');const before=JSON.stringify(s);cashSummary(s,now);cashLedger(s,a,now);assert.equal(JSON.stringify(s),before);validateState(s);});
