import test from 'node:test';
import assert from 'node:assert/strict';
import { emptyState } from '../data/defaults.js';
import { focusOverview, limitValues, limitBasis, saveFocusLimit } from '../js/focus.js';
import { focusHome, moreView } from '../js/focus-ui.js';
const at='2026-10-08T15:00:00';
function state(){const s=emptyState();s.configured=true;Object.assign(s.settings,{income:4000000,sharedBudget:2000000,personalBudgets:{p1:200000,p2:200000},savingsTarget:1000000});return s;}
function tx(extra={}){return {id:'t',sourceId:'t',date:'2026-10-08',datetime:'2026-10-08T10:00:00',amount:100000,direction:'expense',scope:'shared',category:'groceries',merchantRaw:'마트',paymentMethod:'계좌',owner:'p1',...extra};}
test('primary remaining is the explicit consumption limit, not affordability or cash',()=>{const s=state();s.settings.income=1500000;s.transactions=[tx()];const f=focusOverview(s,'2026-09',at);assert.equal(f.limit,2400000);assert.equal(f.remaining,2300000);assert.equal(f.money.d.remaining,400000);assert.equal(f.cash.accounts.length,0);});
test('fixed payment is not added again to consumption-limit usage',()=>{const s=state();s.transactions=[tx(),tx({id:'fixed',scope:'fixed',costKind:'fixed',amount:500000})];const f=focusOverview(s,'2026-09',at);assert.equal(f.used,100000);assert.equal(f.remaining,2300000);});
test('unregistered cash is not presented as a zero or an inferred balance',()=>{const html=focusHome(state(),'2026-09');assert.match(html,/data-focus-value="cash">입력 필요/);});
test('measured cash does not silently become ledger-estimated cash',()=>{const s=state();s.cashAccounts=[{id:'a',name:'계좌',owner:'p1',openingBalance:500000,openingAt:'2026-10-08T09:00:00',reserved:50000,paymentMethod:'계좌',autoMatch:true}];s.transactions=[tx()];const f=focusOverview(s,'2026-09',at);assert.equal(f.cash.usable,450000);assert.equal(f.cash.expected,400000);assert.equal(f.cashChanged,true);assert.equal(f.cashIssue,true);});
test('old cash observations and discrepancies trigger a recheck',()=>{const s=state();s.cashAccounts=[{id:'a',name:'계좌',owner:'p1',openingBalance:500000,openingAt:'2026-10-07T09:00:00',reserved:0,paymentMethod:'',autoMatch:false}];assert.equal(focusOverview(s,'2026-09',at).cashStale,true);});
test('three primary regions only; supporting information remains in closed disclosures',()=>{const s=state();const html=focusHome(s,'2026-09');assert.equal((html.match(/data-focus-value="(?:remaining|cash|fixed)"/g)||[]).length,3);assert.equal((html.match(/data-focus-fold=/g)||[]).length,4);assert.ok(!/<details[^>]*\bopen\b/.test(html));assert.ok(!html.includes('money-summary'));assert.ok(!html.includes('cash-metrics'));});
test('limit editing preserves transactions, cash, future defaults, income, savings and other months',()=>{const s=state();s.transactions=[tx()];s.settings.monthOverrides={'2026-09':{savingsTarget:500000,categoryBudgets:{groceries:120000}},'2026-10':{income:4100000}};const before=structuredClone(s);saveFocusLimit(s,'2026-09',limitValues(2100000,200000,200000),limitBasis(s,'2026-09'));assert.equal(s.settings.monthOverrides['2026-09'].sharedBudget,1700000);assert.equal(s.settings.monthOverrides['2026-09'].savingsTarget,500000);assert.deepEqual(s.settings.monthOverrides['2026-09'].categoryBudgets,{groceries:120000});assert.deepEqual(s.settings.monthOverrides['2026-10'],before.settings.monthOverrides['2026-10']);assert.equal(s.settings.sharedBudget,before.settings.sharedBudget);assert.equal(s.settings.income,before.settings.income);assert.deepEqual(s.transactions,before.transactions);assert.deepEqual(s.cashAccounts,before.cashAccounts);});
test('plan updates reject conflicting changes and invalid allowance totals',()=>{const s=state(),basis=limitBasis(s,'2026-09');s.settings.sharedBudget+=1;assert.throws(()=>saveFocusLimit(s,'2026-09',limitValues(500000,0,0),basis),/다른 기기/);for(const x of [[100,100,100],[-1,0,0],[1.1,0,0],[Infinity,0,0]])assert.throws(()=>limitValues(...x));});
test('overview and markup never mutate source; all old menu routes remain reachable',()=>{const s=state(),before=JSON.stringify(s);focusHome(s,'2026-09');const html=moreView(s,'2026-09');for(const action of ['go-budget','go-review','go-analytics','go-import','go-settings','month-income'])assert.ok(html.includes(action));assert.equal(JSON.stringify(s),before);});
