import test from "node:test";
import assert from "node:assert/strict";
import { emptyState } from "../data/defaults.js";
import { moneyOverview, registeredPayments, syncCategories, reviewRows, confirmCategory, classification, paymentStatus } from "../js/money.js";
import { moneyHome, recurringView, reviewView, cycleStrip } from "../js/views/money.js";
import { validateState } from "../js/models.js";
import { periodKey } from "../js/period.js";
function state() { const s=emptyState();s.configured=true;s.settings.income=6500000;s.settings.sharedBudget=2400000;s.settings.personalBudgets={p1:400000,p2:400000};s.settings.savingsTarget=1000000;return s; }
function tx(id, extras={}) {return {id,sourceId:id,date:"2026-09-15",datetime:"2026-09-15T12:00:00",owner:"p1",amount:10000,direction:"expense",category:"groceries",merchantRaw:"마트",merchantNormalized:"마트",scope:"shared",paymentMethod:"테스트 카드",note:"",sourceType:"xls",costKind:"variable",excluded:false,deletedAt:null,...extras};}
function recurring(id, extras={}) {return {id,name:id,day:15,amount:100000,category:"finance",owner:"p1",scope:"fixed",start:"2026-01-01",end:"",changes:[],paymentMethod:"",merchantPattern:id,...extras};}
test("cycle on 9th and 10th, year and leap boundaries",()=>{
 assert.equal(periodKey("2026-10-09",10),"2026-09");assert.equal(periodKey("2026-10-10",10),"2026-10");
 for(const [month,start,end] of [["2026-09","2026-09-10","2026-10-09"],["2026-12","2026-12-10","2027-01-09"],["2028-02","2028-02-10","2028-03-09"]]){const o=moneyOverview(state(),month,end);assert.equal(o.d.p.start,start);assert.equal(o.d.p.end,end);}
});
test("planned income is never presented as actual income",()=>{const o=moneyOverview(state(),"2026-09","2026-10-08");assert.equal(o.d.b.actualIncome,0);assert.equal(o.d.b.income,6500000);assert.equal(o.stale,true);});
test("salary dates are schedules only; next cycle dates excluded",()=>{const s=state();const o=moneyOverview(s,"2026-09","2026-10-08");assert.deepEqual(o.salaryDates,["2026-09-10","2026-09-15"]);assert.equal(s.transactions.length,0);});
test("fixed budget and paid schedule are counted once",()=>{const s=state();s.recurring=[recurring("r")];s.transactions=[tx("variable",{amount:250000})];let o=moneyOverview(s,"2026-09","2026-10-08");const before=o.d.remaining;assert.equal(o.unpaid,100000);s.transactions.push(tx("payment",{amount:100000,recurringId:"r",scope:"fixed",costKind:"fixed"}));o=moneyOverview(s,"2026-09","2026-10-08");assert.equal(o.d.remaining,before);assert.equal(o.unpaid,0);assert.equal(o.paid,100000);assert.equal(o.d.b.spent,350000);});
test("allowance reserve and shared spending remain disjoint",()=>{const s=state();s.transactions=[tx("shared",{amount:100000}),tx("personal",{scope:"p1",amount:50000})];const o=moneyOverview(s,"2026-09","2026-10-08");assert.equal(o.d.remaining,3050000);assert.equal(o.sharedRemaining,2300000);assert.equal(o.allowanceReserve,750000);assert.equal(o.allowances[0].remaining,350000);});
test("low income caps the shared money without stealing reserved allowance",()=>{const s=state();s.settings.income=1500000;const o=moneyOverview(s,"2026-09","2026-10-08");assert.equal(o.d.budget,500000);assert.equal(o.sharedRemaining,-300000);});
test("unclassified expenses and refunds stay in money totals",()=>{const s=state();s.transactions=[tx("unknown",{merchantRaw:"모름",merchantNormalized:"모름",category:"other",amount:50000}),tx("refund",{merchantRaw:"모름",merchantNormalized:"모름",category:"other",direction:"refund",amount:20000})];const o=moneyOverview(s,"2026-09","2026-10-08");assert.equal(o.pending.length,2);assert.equal(o.pendingAmount,30000);assert.equal(o.d.b.spent,30000);assert.equal(o.d.remaining,3170000);});
test("deleted excluded transfers fixed and split parents are not review tasks",()=>{const s=state();s.transactions=[tx("a",{category:"other",deletedAt:"x"}),tx("b",{category:"other",excluded:true}),tx("c",{category:"other",direction:"transfer"}),tx("d",{category:"other",scope:"fixed"}),tx("e",{category:"other",splitParent:true})];assert.equal(reviewRows(s,"2026-09",true).length,0);});
test("only safe unresolved merchants auto classify, metadata and money unchanged",()=>{const s=state();s.transactions=[tx("safe",{category:"other",merchantRaw:"이마트",merchantNormalized:"이마트"}),tx("pg",{category:"other",merchantRaw:"네이버페이",merchantNormalized:"네이버페이"}),tx("manual",{category:"other",merchantRaw:"이마트",merchantNormalized:"이마트",categoryConfirmed:true})];const before=structuredClone(s.transactions);assert.equal(syncCategories(s),1);assert.equal(s.transactions[0].category,"groceries");assert.equal(s.transactions[1].category,"other");assert.equal(s.transactions[2].category,"other");assert.equal(syncCategories(s),0);s.transactions.forEach((t,i)=>{assert.equal(t.amount,before[i].amount);assert.equal(t.date,before[i].date);assert.equal(t.scope,before[i].scope);});});
test("explicit other confirmation removes review without creating a transaction",()=>{const s=state();s.transactions=[tx("a",{category:"other",merchantRaw:"모름",merchantNormalized:"모름"})];confirmCategory(s,"a","other","물품 확인",false);assert.equal(reviewRows(s,"2026-09",true).length,0);assert.equal(s.transactions.length,1);assert.equal(s.transactions[0].amount,10000);});
test("generic payment names never create broad rules",()=>{const s=state();s.transactions=[tx("a",{category:"other",merchantRaw:"네이버페이",merchantNormalized:"네이버페이"}),tx("b",{category:"other",merchantRaw:"네이버페이",merchantNormalized:"네이버페이"})];confirmCategory(s,"a","child","아이 용품",true);assert.equal(s.rules.length,0);assert.equal(classification(s.transactions[1],s).pending,true);});
test("learning an exact merchant preserves already confirmed categories",()=>{const s=state();s.transactions=[tx("a",{category:"other",merchantNormalized:"독립 상점"}),tx("b",{category:"other",merchantNormalized:"독립 상점"}),tx("c",{category:"health",categoryConfirmed:true,merchantNormalized:"독립 상점"})];confirmCategory(s,"a","living","확인",true);assert.equal(s.transactions[1].category,"living");assert.equal(s.transactions[2].category,"health");assert.equal(s.rules[0].match,"exact");});
test("all registered recurring includes future items, cycle total excludes them",()=>{const s=state();s.recurring=[recurring("old",{day:8}),recurring("new",{day:20,start:"2026-10-01"})];const o=moneyOverview(s,"2026-09","2026-10-08");assert.equal(o.recurring.length,1);assert.equal(o.recurring[0].date,"2026-10-08");assert.equal(registeredPayments(s,"2026-09","2026-10-08").length,2);assert.equal(o.total,100000);});
test("amount changes use occurrence date and preserve original record",()=>{const s=state();s.recurring=[recurring("r",{day:8,changes:[{effective:"2026-10-01",amount:120000}],policyBreakdown:[{product:"test",amount:100000}]})];const before=JSON.stringify(s.recurring);const o=moneyOverview(s,"2026-09","2026-10-08");assert.equal(o.total,120000);assert.equal(JSON.stringify(s.recurring),before);});
test("past scheduled date without a transaction is unconfirmed, not paid",()=>{assert.equal(paymentStatus({paid:false,actual:0,date:"2026-09-15"},"2026-10-08"),"check");assert.equal(paymentStatus({paid:false,actual:100,date:"2026-09-15"},"2026-10-08"),"partial");});
test("private review does not expose merchant, note or payment in markup or search",()=>{const s=state();s.transactions=[tx("private",{scope:"p1",category:"other",merchantRaw:"비밀 가게",merchantNormalized:"비밀 가게",paymentMethod:"비밀 계좌",note:"비밀 메모"})];const html=reviewView(s,"2026-09",{mode:"all"});for(const word of ["비밀 가게","비밀 계좌","비밀 메모"])assert.ok(!html.includes(word));const search=reviewView(s,"2026-09",{mode:"all",query:"비밀 가게"});assert.ok(!search.includes('class="card review-item"'));});
test("all new views escape external strings and render meaningful controls",()=>{const s=state();s.settings.members.p1='<img src=x onerror="alert(1)">';s.recurring=[recurring("r",{name:"<script>oops</script>"})];s.transactions=[tx("x",{category:"other",merchantRaw:"<script>oops</script>",merchantNormalized:"oops"})];for(const html of [moneyHome(s,"2026-09"),reviewView(s,"2026-09"),recurringView(s,"2026-09"),cycleStrip(s,"2026-09")]){assert.ok(!html.includes("<script>"));assert.ok(!html.includes("<img src=x"));assert.ok(html.length>100);}validateState(s);});
test("read-only overview never alters the source state",()=>{const s=state();s.recurring=[recurring("r")];s.transactions=[tx("x")];const before=JSON.stringify(s);moneyOverview(s,"2026-09","2026-10-08");registeredPayments(s,"2026-09","2026-10-08");reviewRows(s,"2026-09",true);assert.equal(JSON.stringify(s),before);});
