import { VERSION } from "../../data/defaults.js";
import { escape as e, won } from "../format.js";
import { icon, button, sectionTitle } from "../ui.js";
export function settingsView(state) {
  const s = state.settings;
  const row = (name, description, action, i) =>
    `<button class="settings-row" data-action="${action}"><span class="setting-icon">${icon(i)}</span><span><strong>${name}</strong><small>${e(description)}</small></span>${icon("chevron")}</button>`;
  return `<div class="page-intro"><div><h1>설정</h1><p>우리집에 맞게, 우리 기기 안에서.</p></div><span class="version-tag">v${VERSION}</span></div><div class="two-column settings-layout"><div class="stack"><section class="card">${sectionTitle("우리집 기본 설정")}${row("수입 · 생활비 · 용돈", `기본 월수입 ${won(s.income)} · 월별 수입은 홈에서 수정해요`, "household", "home")}${row("구성원 이름", `${s.members.p1} · ${s.members.p2}`, "members", "heart")}${row("카드 실적목표", `${s.cardName} · 월 ${won(s.cardTarget)}`, "card-settings", "wallet")}<div class="settings-row"><span class="setting-icon">${icon("eye")}</span><span><strong>개인 내역 숨기기</strong><small>공동 화면에서 개인 가맹점·메모를 가려요</small></span><button role="switch" aria-checked="${s.privacy}" aria-label="개인 내역 숨기기" class="switch ${s.privacy ? "on" : ""}" data-action="privacy"></button></div><p class="settings-footnote">개인 숨김은 화면 표시 기능이에요. 기기 접근을 막는 PIN이나 데이터 암호화 기능은 아니에요.</p></section><section class="card">${sectionTitle("분류와 계획")}${row("고정비 · 반복결제", `${state.recurring.length}개 · 적용일별 금액 변경 지원`, "recurring-list", "repeat")}${row("자동분류 규칙", `${state.rules.length}개 · 가맹점과 결제수단 기준`, "rules-list", "filter")}${row("카테고리", `${state.categories.filter((c) => !c.archived).length}개 사용 중`, "categories-list", "list")}${row("저축목표", "월 배정액과 모은 금액 관리", "go-budget", "chart")}</section></div><div class="stack"><section class="card">${sectionTitle("내 데이터")}${row("거래파일 가져오기", "CSV · XLS · XLSX, 이 기기에서만 처리", "go-import", "upload")}${row("암호화 백업 만들기", "비밀번호로 보호한 파일을 기기에 저장", "backup", "download")}${row("백업 · 초기설정 가져오기", "복원 전 내용을 확인해요", "restore", "upload")}${row("샘플로 둘러보기", "실제 데이터와 분리된 가상 공간", "sample", "sun")}${row("전체 로컬데이터 삭제", "현재 공간의 모든 기록과 설정 초기화", "delete-all", "trash")}</section><section class="card">${sectionTitle("앱과 개인정보")}${row("홈 화면에 설치하기", "앱처럼 열고 오프라인에서도 확인해요", "install", "phone")}${row("개인정보 안내", "금융파일 외부 전송·광고·추적 없음", "privacy-info", "shield")}<div class="local-storage-note">${icon("lock")}<div><strong>이 기기가 우리집 가계부예요</strong><p>서버 동기화가 없으므로 다른 기기에는 암호화 백업으로 옮겨 주세요. 브라우저 데이터 삭제 전에는 꼭 백업해 주세요.</p></div></div></section></div></div>`;
}
