import fs from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
const root = path.resolve("."),
  out = path.join(root, "dist");
await fs.mkdir(out, { recursive: true });
const files = [];
async function copy(file) {
  const source = path.join(root, file),
    stat = await fs.stat(source);
  if (stat.isDirectory()) {
    for (const child of await fs.readdir(source))
      await copy(path.posix.join(file, child));
    return;
  }
  if (file.endsWith(".md")) return;
  await fs.mkdir(path.dirname(path.join(out, file)), { recursive: true });
  await fs.copyFile(source, path.join(out, file));
  files.push(file);
}
for (const file of [
  "index.html",
  "manifest.webmanifest",
  ".nojekyll",
  "css",
  "js",
  "data",
  "assets",
  "vendor",
])
  await copy(file);
let revision = "local";
try {
  revision = execFileSync("git", ["rev-parse", "HEAD"], {
    encoding: "utf8",
  }).trim();
} catch {}
const hash = createHash("sha256");
for (const file of [...files].sort()) {
  hash.update(file);
  hash.update(await fs.readFile(path.join(out, file)));
}
const cache = "richkkok-v1-" + hash.digest("hex").slice(0, 12);
const sw = `/* Generated by scripts/build.mjs */\nconst CACHE=${JSON.stringify(cache)};\nconst FILES=${JSON.stringify(files.filter((f) => !f.endsWith(".txt") && f !== ".nojekyll"))};\nconst ALLOWED=new Set(FILES.map(f=>new URL(f,self.registration.scope).pathname));\nself.addEventListener('install',event=>event.waitUntil((async()=>{try{const cache=await caches.open(CACHE);await cache.addAll(FILES.map(f=>new Request(f,{cache:'reload'})));}catch(error){await caches.delete(CACHE);throw error;}})()));\nself.addEventListener('activate',event=>event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith('richkkok-v1-')&&key!==CACHE)await caches.delete(key);await self.clients.claim();})()));\nself.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')event.waitUntil(self.skipWaiting());});\nself.addEventListener('fetch',event=>{const req=event.request,url=new URL(req.url);if(req.method!=='GET'||url.origin!==self.location.origin)return;if(req.mode!=='navigate'&&!ALLOWED.has(url.pathname))return;event.respondWith((async()=>{const cache=await caches.open(CACHE);const hit=await cache.match(req.mode==='navigate'?'index.html':url.pathname,{ignoreSearch:true});return hit||fetch(req);})());});\n`;
await fs.writeFile(path.join(out, "sw.js"), sw);
await fs.writeFile(path.join(root, "sw.js"), sw);
await fs.writeFile(
  path.join(out, "build.json"),
  JSON.stringify({ version: "2.0.0", commit: revision, cache }),
);
console.log(JSON.stringify({ files: files.length, cache, commit: revision }));
